apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secret.name }}-db-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: {{ include "orders.secretName" . }}
    
  dataFrom:
  - extract:
      key: prod/orders/postgres # This is the name of your secret in AWS
    
# We can map it like this:
#  data:
#    # This maps the Username
#    - secretKey: RETAIL_ORDERS_PERSISTENCE_USERNAME  # Name in K8s
#      remoteRef:
#        key: prod/orders/postgres # The "box" in AWS
#        property: DB_USER # The "Key" in AWS

    # This maps the Password
#    - secretKey: RETAIL_ORDERS_PERSISTENCE_PASSWORD  # Name in K8s
#      remoteRef:
#        key: prod/orders/postgres # The "box" in AWS
#        property: DB_PASS # The "Key" in AWS

#                     OR

# If the keys and values are as is for the app and in our AWS
# secrets manager we can use it like this:

