apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  namespace: retail-app
  labels:
    app: ui
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      # Pod-level security settings
      securityContext:
        fsGroup: 1000
      containers:
      - name: ui-app
        image: sonuparit/retail-app:ui-small
        
        # Container-level security settings
        securityContext:
          runAsUser: 1000
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
            add: ["NET_BIND_SERVICE"]
            
        resources:
          limits:
            cpu: 256m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        env:
        - name: JAVA_OPTS
          value: -XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom
            
        - name: RETAIL_UI_ENDPOINTS_CATALOG
          value: http://catalog-service:8080
        
        - name: RETAIL_UI_ENDPOINTS_CARTS
          value: http://carts-service:8080
        
        - name: RETAIL_UI_ENDPOINTS_CHECKOUT
          value: http://checkout-service:8080
          
         - name: RETAIL_UI_ENDPOINTS_ORDERS
          value: http://orders-service:8080
        
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health/
            port: 8080
          initialDelaySeconds: 30
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
      - name: tmp-volume
        emptyDir:
          medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: retail-app
spec:
  selector:
    app: ui
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080