# deployment.yaml
apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "orders.fullname" . }}-exp
  labels:
    app: {{ include "orders.fullname" . }}-exp

spec:
  replicas: {{ .Values.exporterReplica }}

  selector:
    matchLabels:
      app: {{ include "orders.fullname" . }}-exp

  template:
    metadata:
      labels:
        app: {{ include "orders.fullname" . }}-exp

    spec:
      containers:
        - name: postgres-exporter

          image: quay.io/prometheuscommunity/postgres-exporter:v0.18.0

          ports:
            - containerPort: 9187
              name: metrics

          env:

            - name: DATA_SOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}-secret
                  key: RETAIL_ORDERS_PERSISTENCE_USERNAME

            - name: DATA_SOURCE_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}-secret
                  key: RETAIL_ORDERS_PERSISTENCE_PASSWORD

            - name: DATA_SOURCE_URI
              value: "{{ include "orders.fullname" . }}-headless.{{ .Release.Namespace }}.svc.cluster.local:5432/{{ .Values.env.orders.name }}?sslmode=disable"

            - name: DATA_SOURCE_NAME
              value: "postgresql://$(DATA_SOURCE_USER):$(DATA_SOURCE_PASS)@$(DATA_SOURCE_URI)"

          args:
            - "--disable-settings-metrics"
            - "--disable-default-metrics"

          resources:
            requests:
              cpu: 50m
              memory: 64Mi

            limits:
              cpu: 200m
              memory: 256Mi

{{/*
#          readinessProbe:
#            httpGet:
#              path: /metrics
#              port: 9187
#              scheme: HTTP
#
#            initialDelaySeconds: 20
#            periodSeconds: 10
#            timeoutSeconds: 5
#            successThreshold: 1
#            failureThreshold: 5
*/}}

          livenessProbe:
            httpGet:
              path: /metrics
              port: 9187
              scheme: HTTP

            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 5