{{- if .Values.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "carts.configMapName" . }}
data:
  JAVA_OPTS: {{ .Values.env.java.options | quote }}
  SERVER_TOMCAT_ACCESSLOG_ENABLED: {{ .Values.env.tomcatServer.enabled | quote }}
  RETAIL_CART_PERSISTENCE_PROVIDER: {{ .Values.env.table.provider | quote }}
  AWS_REGION: {{ .Values.env.table.awsRegion | quote }}
  RETAIL_CART_PERSISTENCE_DYNAMODB_TABLE_NAME: {{ .Values.env.table.tableName | quote }}
  RETAIL_CART_PERSISTENCE_DYNAMODB_CREATE_TABLE: {{ .Values.env.table.createTable | quote }}
  RETAIL_CART_PERSISTENCE_DYNAMODB_ENDPOINT: ""
{{- end }}