server:
  service:
    type: ClusterIP   # we will expose later via ingress

configs:
  params:
    server.insecure: true   # easier for local / kind

  cm:
    application.instanceLabelKey: argocd.argoproj.io/instance

controller:
  replicas: 1

repoServer:
  autoscaling:
    enabled: false