{{- if .Values.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orders.configMapName" . }}-sts-cm
data:
  PGDATA: {{ .Values.env.postgres.pgdata | quote }}
  POSTGRES_DB: {{ .Values.env.orders.name | quote }}
{{- end }}
