prometheus:
  enabled: true
  prometheusSpec:
    retention: 7d
      #    additionalScrapeConfigsSecret:
      # enabled: true
      # name: additional-scrape-configs
      # key: ../postgresql/additional-scrape-configs.yaml
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi

    serviceMonitorSelectorNilUsesHelmValues: false

grafana:
  enabled: true

  adminPassword: admin123

  service:
    type: ClusterIP

  persistence:
    enabled: true
    size: 5Gi
    
  ingress:
    enabled: false

  defaultDashboardsEnabled: true
  
  resources:
    requests:
      memory: 256Mi
      cpu: 100m

    limits:
      memory: 512Mi
      cpu: 500m

alertmanager:
  enabled: true
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi  

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheusOperator:
  enabled: true

