replicaCount: 1

image:
  repository: sonuparit/retail-app
  pullPolicy: IfNotPresent
  tag: "ui-small"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

configMap:
  create: true
  name:
env:
  endpoints:
    carts: # http://carts-service:8080
    catalog: # http://catalog-service:8080
    checkout: # http://checkout-service:8080
    orders: # http://orders-service:8080
  java:
    options: "-XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom"

securityContext:
  runAsUser: 1000
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
    add: ["NET_BIND_SERVICE"]

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
  - name: gateway
    sectionName: http
  hostnames:
  - chart-example.local
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /headers

resources:
  limits:
    cpu: 256m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
    
livenessProbe:
  httpGet:
    path: /actuator/health/
    port: 8080
  initialDelaySeconds: 30
  timeoutSeconds: 20
  
# readinessProbe:
#   httpGet:
#     path: /
#     port: http
  
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes:
- name: tmp-volume
  emptyDir:
    medium: Memory

volumeMounts:
- name: tmp-volume
  mountPath: /tmp

nodeSelector: {}

tolerations: []

affinity: {}
