apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: retail-matrix
  namespace: argocd

spec:
  generators:
    - matrix:
        generators:

          # 🔹 Services
          - list:
              elements:
                - name: secrets
                  chartPath: "charts/secret-configs"
                  wave: "2"
                - name: carts
                  chartPath: charts/carts
                  wave: "3"

                - name: catalog
                  chartPath: charts/catalog
                  wave: "3"

                - name: checkout
                  chartPath: charts/checkout
                  wave: "3"

                - name: orders
                  chartPath: charts/orders
                  wave: "3"

                - name: ui
                  chartPath: charts/ui
                  wave: "4"

          # 🔹 Environments
          - list:
              elements:
                - env: dev
                  namespace: dev
#                - env: stage
#                  namespace: stage
#                - env: prod
#                  namespace: prod

  template:
    metadata:
      name: "{{name}}-{{env}}"
      labels:
        app.kubernetes.io/name: "{{name}}"
        env: "{{env}}"
      annotations:
        argocd.argoproj.io/sync-wave: "{{wave}}"

    spec:
      project: retail-app

      source:
        repoURL: https://github.com/sonuparit/retail-store-reverse-engineered.git
        targetRevision: main
        path: my-work/kubernetes/argocd-deploy/apps/{{chartPath}}

        helm:
          valueFiles:
            - ../../../envs/{{env}}/{{name}}.yaml

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 3
          backoff:
            duration: 20s
            factor: 2
            maxDuration: 2m

        syncOptions:
          - CreateNamespace=true
