# service-monitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: postgres-exporter
  namespace: dev

  labels:
    release: kube-prometheus-stack

spec:
  namespaceSelector:
    matchNames:
    - dev

  selector:
    matchLabels:
      app: postgres-exporter

  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s