# deployment.yaml
apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres-exporter
  namespace: dev
  labels:
    app: postgres-exporter

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres-exporter

  template:
    metadata:
      labels:
        app: postgres-exporter

    spec:
      containers:
        - name: postgres-exporter

          image: quay.io/prometheuscommunity/postgres-exporter:v0.18.0

          ports:
            - containerPort: 9187
              name: metrics

          envFrom:
            - secretRef:
                name: postgres-exporter-secret

          args:
            - "--disable-settings-metrics"
            - "--disable-default-metrics"

          resources:
            requests:
              cpu: 50m
              memory: 64Mi

            limits:
              cpu: 200m
              memory: 256Mi

#          readinessProbe:
#            httpGet:
#              path: /metrics
#              port: 9187
#              scheme: HTTP
#
#            initialDelaySeconds: 20
#           periodSeconds: 10
#            timeoutSeconds: 5
#            successThreshold: 1
#            failureThreshold: 5
#
#          livenessProbe:
#            httpGet:
#              path: /metrics
#              port: 9187
#              scheme: HTTP
#
#            initialDelaySeconds: 90
#            periodSeconds: 20
#            timeoutSeconds: 10
#            successThreshold: 1
#            failureThreshold: 5
