apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-x-secret
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: alertmanager-secret
    template:
      data:
        alertmanager.yaml: |
          global:
            resolve_timeout: 5m
            smtp_smarthost: 'smtp.gmail.com:587'
            smtp_from: 'sonu.parit1@gmail.com'
            smtp_auth_username: 'sonu.parit1@gmail.com'
            smtp_auth_password: '{{ .SMTP_PASSWORD }}'
            smtp_require_tls: true
            
          route:
            group_by: ['alertname', 'namespace']
            group_wait: 30s
            group_interval: 5m
            repeat_interval: 3h
            receiver: 'multi-receiver'
            
          receivers:
            - name: 'multi-receiver'
              slack_configs:
                - api_url: '{{ .SLACK_URL }}'
                  channel: "#alerts"
                  send_resolved: true
                  title: "[{{ `{{` }} .Status | toUpper {{ `}}` }}] {{ `{{` }} .CommonLabels.alertname {{ `}}` }}"
                  text: |
                    Alert: {{ `{{` }} .CommonLabels.alertname {{ `}}` }}
                    Severity: {{ `{{` }} .CommonLabels.severity {{ `}}` }}
                    Description: {{ `{{` }} .CommonAnnotations.description {{ `}}` }}
                    
              email_configs:
                - to: 'sonu.parit1@gmail.com'
                  send_resolved: true
  data:
    - secretKey: SLACK_URL
      remoteRef:
        key: prod/alertmanager/email_slack
        property: slack_url

    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: prod/alertmanager/email_slack
        property: smtp_password
