apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default

  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 2.4.1
    helm:
      values: |
        installCRDs: true
        webhook:
          port: 9443
          # Enabling these ensures ArgoCD waits for the webhook to be alive
          readinessProbe:
            enabled: true
        certController:
          enabled: true # Necessary for the webhook TLS

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true # 👈 This allows the parent to ignore the "Unknown Resource" error
      - ServerSideApply=true # 👈 This fixes the "apply" errors for large CRDs

    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m