apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      # Since we are on EC2 with an IAM Role, we don't need to provide keys here
      region: ap-south-1 # Change to your region
