# secret.yaml
apiVersion: v1
kind: Secret

metadata:
  name: postgres-exporter-secret
  namespace: dev

type: Opaque

stringData:
  # postgresql://USERNAME:PASSWORD@HOST:PORT/DATABASE?sslmode=disable
  DATA_SOURCE_NAME: "postgresql://orders_xxxx:xxxxxxxx@orders-dev-headless.dev.svc.cluster.local:5432/xxxxx?sslmode=disable"
