apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: argocd-server-metrics
  namespace: monitoring

  labels:
    release: kube-prom-stack

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server

  namespaceSelector:
    matchNames:
      - argocd

  endpoints:
    - port: metrics
      interval: 10s
      path: /metrics