replicaCount: 1

env:
  endpoints:
    carts: http://carts-dev-service:8080
    catalog: http://catalog-dev-service:8080
    checkout: http://checkout-dev-service:8080
    orders: http://orders-dev-service:8080