apiVersion: external-secrets.io/v1
# kind: ClusterExternalSecret
kind: ExternalSecret
metadata:
  name: {{ include "orders.fullname" . }}-X-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    # name: {{ include "orders.secretName" . }}
    name: {{ include "orders.fullname" . }}-secret
  dataFrom:
  - extract:
      key: prod/orders/postgres
      
    # name: {{ required "A secret name is required! Please set .Values.secret.name" .Values.secret.name }}-secret
    # name: {{ .Values.secret.name }}-secret
    # 2. Which namespaces get the secret?
    # namespaceSelector:
    # matchExpressions:
    # - key: kubernetes.io/metadata.name
    #   operator: In
    #   values: 
    #     {{ .Values.secret.namespace | indent 10 }}
          
    # matchLabels:
    #   secret-sync: "true"
    
   # This is the name of your secret in AWS
    
# We can map it like this:
#  data:
#    # This maps the Username
#    - secretKey: RETAIL_ORDERS_PERSISTENCE_USERNAME  # Name in K8s
#      remoteRef:
#        key: prod/orders/postgres # The "box" in AWS
#        property: DB_USER # The "Key" in AWS

    # This maps the Password
#    - secretKey: RETAIL_ORDERS_PERSISTENCE_PASSWORD  # Name in K8s
#      remoteRef:
#        key: prod/orders/postgres # The "box" in AWS
#        property: DB_PASS # The "Key" in AWS

#                     OR

# If the keys and values are as is for the app and in our AWS
# secrets manager we can use it like this:

