{{- if .Values.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orders.configMapName" . }}
data:
  RETAIL_ORDERS_PERSISTENCE_PROVIDER: {{ .Values.env.orders.provider | quote }}
# convention
# {Pod Name}.{Headless Service Name}.{Namespace}.svc.cluster.local
# {{ include "orders.fullname" . }}-0.{{ include "orders.fullname" . }}-headless:5432
# {{ include "orders.fullname" . }}-headless:5432
  RETAIL_ORDERS_PERSISTENCE_ENDPOINT: {{ printf "%s-0.%s-headless:%d" (include "orders.fullname" .) (include "orders.fullname" .) (int .Values.dbImage.port) | quote }}
# {{ include "orders.fullname" . }}-headless:5432
# {{ .Values.env.orders.endpoint | quote }}
  RETAIL_ORDERS_PERSISTENCE_NAME: {{ .Values.env.orders.name | quote }}
# Provided via secrets
#  RETAIL_ORDERS_PERSISTENCE_USERNAME: ""
#  RETAIL_ORDERS_PERSISTENCE_PASSWORD: {{ .Values.env.orders.provider | quote }}
  
# RabbitMQ Not using
  RETAIL_ORDERS_MESSAGING_PROVIDER: {{ .Values.env.rabbitmq.provider | quote }}
  RETAIL_ORDERS_MESSAGING_RABBITMQ_ADDRESSES: "" # {{ .Values.env.rabbitmq.address | quote }}
  RETAIL_ORDERS_MESSAGING_RABBITMQ_USERNAME: "" # {{ .Values.env.rabbitmq.username | quote }}
  RETAIL_ORDERS_MESSAGING_RABBITMQ_PASSWORD: "" # {{ .Values.env.rabbitmq.password | quote }}
{{- end }}
