{{- if .Values.hooks.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-secrets
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: hook-sa
      restartPolicy: Never
      containers:
        - name: wait
          image: bitnami/kubectl
          
          {{/* Needs ServiceAccount + ClusterRole + ClusterRoleBinding 
          Wait for K8s reconcile feature, don't increase extra complexities*/}}
          
          command:
            - /bin/sh
            - -c
            - |
                            
              echo "Waiting for ExternalSecret to be Ready..."  
  
              until kubectl get clustersecretstore aws-secretsmanager \
                -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}' \
                | grep True; do

                echo "Waiting for ClusterSecretStore..."
                sleep 5
              done

              echo "ClusterSecretStore is ready 🚀"

{{- end }}