apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: retail-matrix
  namespace: argocd

spec:
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: wave
              operator: In
              values:
                - "12" # ArgoCD waits for 'secrets' (Wave 2) to be Healthy
        - matchExpressions:
            - key: wave
              operator: In
              values:
                - "13" # Then it moves to carts, catalog, etc. (Wave 3)
        - matchExpressions:
            - key: wave
              operator: In
              values:
                - "14" # Finally it deploys the UI (Wave 4)

  generators:
    - matrix:
        generators:
          # 🔹 Services
          - list:
              elements:
                - name: secrets
                  chartPath: "charts/secret-configs"
                  wave: "12" # Matches the first step above
                  
                - name: carts
                  chartPath: charts/carts
                  wave: "13" # Matches the second step

                - name: catalog
                  chartPath: charts/catalog
                  wave: "13"

                - name: checkout
                  chartPath: charts/checkout
                  wave: "13"

                - name: orders
                  chartPath: charts/orders
                  wave: "13"

                - name: ui
                  chartPath: charts/ui
                  wave: "14" # Matches the third step

          # 🔹 Environments
          - list:
              elements:
                - env: dev
                  namespace: dev
#                - env: stage
#                  namespace: stage
#                - env: prod
#                  namespace: prod

  template:
    metadata:
      name: "{{name}}-{{env}}"
      labels:
        # CRITICAL: The strategy uses these labels to group the apps
        wave: "{{wave}}" 
        app.kubernetes.io/name: "{{name}}"
        env: "{{env}}"
      annotations:
        argocd.argoproj.io/sync-wave: "{{wave}}"

    spec:
      project: retail-app
      source:
        repoURL: https://github.com/sonuparit/retail-store-reverse-engineered.git
        targetRevision: main
        path: my-work/04-applications/kubernetes/argocd-deploy/apps/{{chartPath}}
        helm:
          valueFiles:
            - ../../../envs/{{env}}/{{name}}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true