environments:
  kind:
    values:
      - values/kind-ec2.yaml
  prod:
    values:
      - values/eks-prod.yaml

releases:
  # 1. Deploy Secrets First
  - name: secrets
    chart: ./charts/secret-configs
    namespace: retail-app
    labels:
      tier: secrets
    wait: true # Ensures secrets are fetched before other apps start

  # 2. Deploy the Database/StatefulSet app
  - name: orders-db
    chart: ./charts/orders
    namespace: retail-app
    labels:
      tier: orders
    needs:
      - secrets
    values:
      - ./charts/orders/values.yaml
      - db:
          createStorageClass: {{ .Values.db.createStorageClass }}

  # 3. Deploy the other Microservices
  - name: carts
    chart: ./charts/carts
    namespace: retail-app
    labels:
      tier: carts

  - name: catalog
    chart: ./charts/catalog
    namespace: retail-app
    labels:
      tier: catalog

  - name: checkout
    chart: ./charts/checkout
    namespace: retail-app
    labels:
      tier: checkout

  - name: ui
    chart: ./charts/ui
    namespace: retail-app
    labels:
      tier: ui